apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeai-server
  namespace: bee-prod-internal
  labels:
    app: beeai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeai-server
  template:
    metadata:
      labels:
        app: beeai-server
    spec:
      containers:
      - name: beeai-server
        image: ghcr.io/i-am-bee/beeai/beeai-server:latest
        ports:
        - name: acp
          containerPort: 8333
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "4"
            memory: "4Gi"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: beeai-server
  namespace: bee-prod-internal
spec:
  selector:
    app: beeai-server
  ports:
    - protocol: TCP
      port: 8333
      targetPort: acp
  type: ClusterIP