apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeai-web
  namespace: bee-prod-internal
  labels:
    app: beeai-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeai-web
  template:
    metadata:
      labels:
        app: beeai-web
    spec:
      containers:
      - name: beeai-web
        image: ghcr.io/i-am-bee/beeai/beeai-web:latest
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: ACP_CLIENT_SERVER_URL
          value: "http://beeai-server.bee-prod-internal.svc.cluster.local:8333/mcp/sse"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: beeai-web
  namespace: bee-prod-internal
spec:
  selector:
    app: beeai-web
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: http
  type: ClusterIP